### ISSUE TITLE
Blog Article with linked author leads tu imidiat crash of the App.

### ISSUE THREAD

**Issue by Gradlon** [apostrophecms/apostrophe-enterprise-testbed#18]
Hello, I have an Issue with Apostrophe which is 100% reproducible for me on the testbed.
The Error:
`C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\apostrophe-workflow\lib\api.js:568
    if (locale.match(/-draft$/)) {
               ^

TypeError: Cannot read property 'match' of undefined
    at Object.self.draftify (C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\apostrophe-workflow\lib\api.js:568:16)
    at getTwo (C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\apostrophe-workflow\lib\api.js:274:70)
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:718:13
    at iterate (C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:262:13)
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:274:29
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:44:16
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:723:17
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:167:37
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\apostrophe-workflow\lib\api.js:270:16
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\apostrophe\lib\modules\apostrophe-docs\lib\cursor.js:1086:18
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:52:16
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:1209:30
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\apostrophe\lib\modules\apostrophe-docs\lib\cursor.js:1379:18
    at C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:52:16
    at Immediate.<anonymous> (C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:269:32)
    at Immediate.<anonymous> (C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\async\lib\async.js:44:16)
    at Immediate.wrapper (C:\Users\Gradlon\Desktop\apostrophe-enterprise\node_modules\lodash\index.js:3592:19)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)`

Steps to reproduce the error.
1. Clone Repo
2. Install modules
3. Launch app.
4. Login
5. Create an Article and link it to an author.

Result: App Crashes with the above error.

Expected result: Blog article is showing up with information about the author.

Used Node Version 8.0.0
NPM Version 6.0.0
MongoDB 3.4

Kind regards
Gradlon

**Comment by abea** [comment]
@boutell Did this get resolved?

**Comment by boutell** [comment]
Following the instructions I can no longer reproduce the issue. Must have been corrected at some point. Thanks for the report.
